hmrc/manage-pensions-frontend

- conf/logback.xml
changed the logger level for further debuging
> changed the logger level for further debuging

- conf/logback.xml
> reverted Logger level

- app/controllers/InviteController.scala
- app/models/MinimalPSA.scala
- conf/application.conf
- test/connectors/MinimalPsaConnectorSpec.scala
- test/connectors/SchemeDetailsConnectorSpec.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/InviteControllerSpec.scala
- test/controllers/ListSchemesControllerSpec.scala
- test/controllers/RetrievalsSpec.scala
- test/controllers/SchemesOverviewControllerSpec.scala
- test/controllers/YouCannotSendAnInviteControllerSpec.scala
- test/controllers/YouNeedToRegisterControllerSpec.scala
- test/controllers/actions/FakeAuthAction.scala
- test/controllers/actions/FakeUnAuthorisedAction.scala
- test/resources/data/validMinimalPsaDetails.json
- test/utils/MockDataHelper.scala
PODS-97 : Invite new PSA redirection using psaSuspensionFlag
> PODS-97 : Invite new PSA redirection using psaSuspensionFlag

- conf/application.conf
Reverts hmrc/manage-pensions-frontend#36
> Revert "Rename mongoName"

- conf/messages.en
URL already changed in 313281b
> PODS-1608 - Association (invite a PSA) - update content on inviter suspended page

- app/models/PensionsScheme.scala
- test/testhelpers/CommonBuilders.scala
PODS-1680 : added model for establisher and trustee as part of scheme details
> PODS-1680 : added model for establisher and trustee as part of scheme details

- app/models/PensionsScheme.scala
- test/resources/data/validSchemeDetailsResponse.json
- test/testhelpers/CommonBuilders.scala
PODS-1680 : model updated with correct establisher and trustee type and reads for contact
> PODS-1680 : model updated with correct establisher and trustee type and reads for contact

- app/identifiers/invitations/HaveYouEmployedPensionAdviserId.scala
- app/utils/UserAnswers.scala
PODS-1743 : refactoring - added new method to remove multiple keys
> PODS-1743 : refactoring - added new method to remove multiple keys

- app/config/FrontendAppConfig.scala
- app/views/schemeDetails.scala.html
- conf/application.conf
- test/views/SchemeDetailsViewSpec.scala
PODS-1722 : added link to view scheme details form pensions-scheme-frontend
> PODS-1722 : added link to view scheme details form pensions-scheme-frontend

- app/config/FrontendAppConfig.scala
- conf/application.conf
- test/toggles/FeatureToggleBehaviours.scala
- test/toggles/WorkPackageTwoFeatureToggle.scala
PODS-1847 : Add a toggle for Work Package 2 (remove self as PSA from Scheme
> PODS-1847 : Add a toggle for Work Package 2 (remove self as PSA from Scheme

- app/controllers/remove/ConfirmRemovedController.scala
- app/views/remove/confirmRemoved.scala.html
- conf/messages.en
- test/controllers/remove/ConfirmRemovedControllerSpec.scala
- test/views/remove/ConfirmRemovedViewSpec.scala
Controller done
PODS-1814: add PSA name to dynamic text
> PODS-1814: Confirm PSA has successfully removed themselves

- app/controllers/SchemesOverviewController.scala
- conf/app.routes
- test/controllers/SchemesOverviewControllerSpec.scala
PODS-1751: Redirect /manage-pension-schemes to /manage-pension-schemes/overview
> PODS-1751: Redirect /manage-pension-schemes to /manage-pension-schemes/overview

- app/config/FrontendAppConfig.scala
- app/controllers/DeleteSchemeController.scala
- app/controllers/SchemesOverviewController.scala
- app/utils/Toggles.scala
- conf/application.conf
- test/config/FeatureSwitchManagementServiceSpec.scala
- test/controllers/DeleteSchemeControllerSpec.scala
- test/controllers/SchemesOverviewControllerSpec.scala
PODS-2252: removed the enable-hub-v2 toggle
>  PODS-2252: removed the enable-hub-v2 toggle

- app/DataCacheModule.scala
- app/connectors/PensionAdminCacheConnector.scala
- app/controllers/deregister/SuccessfulDeregistrationController.scala
- app/utils/annotations/PensionAdminCache.java
- test/controllers/deregister/SuccessfulDeregistrationControllerSpec.scala
PODS-2578: isChanged flag is being set when users re-enrol
> PODS-2578: isChanged flag is being set when users re-enrol

- app/controllers/deregister/ConfirmStopBeingPsaController.scala
- app/controllers/deregister/SuccessfulDeregistrationController.scala
- test/controllers/deregister/ConfirmStopBeingPsaControllerSpec.scala
- test/controllers/deregister/SuccessfulDeregistrationControllerSpec.scala
PODS-2578: update the auth action from success page
> PODS-2578: update the auth action from success page

- app/config/FrontendAppConfig.scala
- app/connectors/PensionSchemeVarianceLockConnector.scala
- app/controllers/SchemeDetailsController.scala
- app/models/SchemeVarianceLockModel.scala
- app/views/schemeDetails.scala.html
- conf/application.conf
- test/connectors/PensionSchemeVarianceLockConnectorSpec.scala
- test/controllers/SchemeDetailsControllerSpec.scala
- test/views/SchemeDetailsViewSpec.scala
PODS-2576 : Copy lock repo code from scheme into manager repo
> PODS-2576 : Copy lock repo code from scheme into manager repo 

- test/controllers/SchemeDetailsControllerSpec.scala
PODS-2569: fix for failure test
> PODS-2569: fix for failure test

- app/audit/DeregisterEvent.scala
- test/audit/AuditServiceSpec.scala
I've changed the auditType from PSADeEnrol to PSADeEnrolment (PSADeEnrol is now audited in pension-administrator)
> PODS-2590: Change auditType from PSADeEnrol to PSADeEnrolment

- app/controllers/remove/RemovalDateController.scala
- app/controllers/remove/RemovePsaController.scala
- app/identifiers/AssociatedDateId.scala
- app/models/Admin.scala
- app/models/PsaAssociatedDate.scala
- test/controllers/SchemeDetailsControllerSpec.scala
- test/controllers/remove/RemovalDateControllerSpec.scala
- test/controllers/remove/RemovePsaControllerSpec.scala
PODS-2584 : Scheme variations - fix delete PSA journey
> PODS-2584 : Scheme variations - fix delete PSA journey

- conf/application.conf
PODS-2673: feedback survey updated
> PODS-2673: feedback survey updated

- conf/application.conf
- test/toggles/TogglesSpec.scala
PODS-2805: Toggle on pensions-scheme data shift
> PODS-2805: Toggle on pensions-scheme data shift

- conf/application.conf
Make sure the service doesn't try to render messages in Welsh
> Turn off welsh support

- app/connectors/aft/AFTConnector.scala
- app/services/SchemeDetailsService.scala
- test/services/SchemeDetailsServiceSpec.scala
Reverts hmrc/manage-pensions-frontend#266
> Revert "Using Date helper to set the current date"

- app/views/components/input_date.scala.html
- app/views/remove/removalDate.scala.html
> Pods 4063 External DAC Issue - Fieldset with empty legend A - MANAGE SCHEME

- app/controllers/invitations/InvitationSuccessController.scala
- app/models/MinimalPSA.scala
- app/views/invitations/invitation_success.scala.html
- conf/messages.en
- test/controllers/invitations/InvitationSuccessControllerSpec.scala
- test/views/invitations/InvitationSuccessSpec.scala
Reverts hmrc/manage-pensions-frontend#298
> Revert "Pods 4266"

- app/controllers/invitations/InvitationSuccessController.scala
- app/models/MinimalPSA.scala
- app/views/invitations/invitation_success.scala.html
- conf/messages.en
- test/controllers/invitations/InvitationSuccessControllerSpec.scala
- test/views/invitations/InvitationSuccessSpec.scala
Reverts hmrc/manage-pensions-frontend#300
> Revert "Revert "Pods 4266""

- app/views/components/scheme_list.scala.html
> PODS-4778: table markup changes for accessiblity

- app/controllers/remove/pspSelfRemoval/DeclarationController.scala
- test/controllers/remove/pspSelfRemoval/DeclarationControllerSpec.scala
This reverts commit c65ff2ef150637f9e92580706a9563aebb6bc278.
> PODS-5121 Send confirmation email when PSP deauthorises themselves from a scheme

- app/connectors/admin/MinimalConnector.scala
…rning when checking psp id user types into authorise journey
> PODS-5303 Exception - NotFoundException when entering an invalid psp id on authorise psp journey

- app/services/PspSchemeDashboardService.scala
This id duplicated in psp scheme dashboard return link
> duplicate-schemeid

- conf/messages.en
> PODS-5255-Fixed the dash issue with de-authorise

- conf/messages.en
PODS-5855 : Update Triage Page Content
> PODS-5855 : Update Triage Page Content

- app/controllers/invitations/psa/CheckYourAnswersController.scala
- app/utils/CheckYourAnswersHelper.scala
- app/views/invitations/invitation_success.scala.html
- app/views/invitations/psa/incorrectPsaDetails.scala.html
- app/views/invitations/psa/psaId.scala.html
- app/views/invitations/psa/psaName.scala.html
- app/views/invitations/psa/psa_already_associated.scala.html
- app/views/invitations/psa/whatYouWillNeed.scala.html
- test/controllers/invitations/psa/CheckYourAnswersControllerSpec.scala
- test/utils/CheckYourAnswersHelperSpec.scala
> PODS-6034-upgraded all pages for invitation journey

- app/PODSModule.scala
- app/controllers/psp/ListSchemesController.scala
- app/identifiers/psp/SearchPSTRId.scala
- app/utils/annotations/SearchPstr.java
- app/utils/navigators/SearchNavigator.scala
- conf/app.routes
- project/AppDependencies.scala
- test/controllers/psp/ListSchemesControllerSpec.scala
- test/utils/navigators/SearchNavigatorSpec.scala
need to test for accessiblity after merge
> Pods 6402: focus order

- app/assets/stylesheets/partials/_card.scss
> PODS-6459: color changes

- conf/application.conf
- project/AppDependencies.scala
bootstrap to 5.24 and play-fe to 3.4.
> 7112 - Library updates

- app/config/FrontendAppConfig.scala
- app/controllers/actions/AuthAction.scala
- conf/application.conf
- test/controllers/actions/AuthActionSpec.scala
> PODS-9192: Reverted Cl250 requirement
